; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Tue Aug 08 2017 18:41:34 GMT+0200 (Romance Summer Time)

; Clear any bed transform
M561

; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y130 H0 Z-99999
G30 P2 X285 Y130 H0 Z-99999
G30 P3 X285 Y15 H0 Z-99999 S

