; Configuration file for Duet WiFi (firmware version 1.17)
; More Info https://www.thingiverse.com/thing:2474898
; generated by Pulkkinen on Tue Aug 08 2017 18:41:35 GMT+0200 (Romance Summer Time)

; Clear any bed transform
M561

; Probe the bed at 4 points
G30 P0 X37 Y0 H0 Z-99999
G30 P1 X37 Y103 H0 Z-99999
G30 P2 X248 Y103 H0 Z-99999
G30 P3 X248 Y0 H0 Z-99999 S