; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Tue Aug 08 2017 18:41:35 GMT+0200 (Romance Summer Time)

; Lift Z relatively to current position
G91
G1 Z5 F6000

; Move Z down until the switch triggers
G1 Z-160 S1 F1800

; Back to absolute positioning
G90

; Tell the firmware where we are
G92 Z2.5

; Uncomment the following lines to lift Z after probing
;G91
;G1 Z5 F100
;G90
