; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Aug 08 2017 18:41:35 GMT+0200 (Romance Summer Time)

; Wait for set temperatures to be reached
M116 P0
